backend:
  replicaCount: 2
  config:
    environment: "us-east-1-int"
    log_config:
      level: "info"
      format: "json"
      add_source: true

frontend:
  replicaCount: 1
  config:
    environment: "us-east-1-int"
    backend_url: "http://phasor-backend:8080/instance/info"
    log_config:
      level: "info"
      format: "json"
      add_source: true
    tile_colors:
      - "#667eea"
      - "#f093fb"
      - "#4facfe"
      - "#43e97b"

dapr:
  enabled: false
