apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: localhost-wildcard
  namespace: traefik
spec:
  secretName: localhost-wildcard-tls
  dnsNames:
    - "localhost"
    - "*.localhost"
  issuerRef:
    name: localhost-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
