global:
  mtls:
    enabled: true

  ha:
    enabled: false

  logAsJson: true

dapr_operator:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
  watchNamespace: ""

dapr_placement:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi

dapr_sentry:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
  trustDomain: cluster.local

dapr_sidecar_injector:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
  sidecarRunAsNonRoot: true
  sidecarDropALLCapabilities: true

dapr_dashboard:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
