apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-within-namespace
  namespace: loki
spec:
  rules:
    - from:
        - source:
            namespaces:
              - loki
