apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki-api
  namespace: loki
spec:
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
      sectionName: observability
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /loki
      backendRefs:
        - name: loki-gateway
          port: 80
