apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authorization-policy-allow-alloy.yaml
  - authorization-policy-allow-grafana.yaml
  - authorization-policy-allow-within-namespace.yaml
  - http-route-loki-api.yaml
