backend:
  replicaCount: 1
  config:
    environment: "eu-central-1-dev"
    log_config:
      level: "debug"
      format: "json"
      add_source: true

frontend:
  replicaCount: 1
  config:
    environment: "eu-central-1-dev"
    backend_url: "http://phasor-dev-backend/instance/info"
    log_config:
      level: "debug"
      format: "json"
      add_source: true
    tile_colors:
      - "#667eea"
      - "#f093fb"
      - "#4facfe"
      - "#43e97b"

httpRoute:
  enabled: true
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - phasor.dev.localhost
