apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authorization-policy-allow-alloy-scrape.yaml
  - authorization-policy-allow-argo-rollouts.yaml
  - authorization-policy-allow-istio-gateway.yaml
