apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-wildcard
  namespace: istio-system
spec:
  secretName: dev-wildcard-tls
  dnsNames:
    - "dev.eu-central-1.localhost"
    - "*.dev.eu-central-1.localhost"
  issuerRef:
    name: localhost-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
