apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alloy.yaml
  - argocd.yaml
  - cert-manager.yaml
  - dapr-system.yaml
  - default.yaml
  - grafana.yaml
  - kargo.yaml
  - kube-public.yaml
  - kube-system.yaml
  - loki.yaml
  - mimir.yaml
  - monitoring.yaml
  - phasor.yaml
  - phasor-eu-central-1-dev.yaml
  - phasor-eu-central-1-int.yaml
  - phasor-eu-central-1-prod.yaml
  - phasor-us-east-1-int.yaml
  - phasor-us-east-1-prod.yaml
  - sealed-secrets.yaml
  - tempo.yaml
  - traefik.yaml
