apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-alloy-scrape
  namespace: argo-rollouts
spec:
  rules:
    - from:
        - source:
            namespaces:
              - alloy
      to:
        - operation:
            ports:
              - "8090"
