apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo-rollouts-dashboard
  namespace: argo-rollouts
spec:
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - argo-rollouts.dev.eu-central-1.localhost
  rules:
    - backendRefs:
        - name: argo-rollouts-dashboard
          port: 3100
