# Disabled - replaced by k8s-monitoring (Alloy) + Mimir
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: kube-prometheus-stack
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    argocd.argoproj.io/sync-wave: "-1"
#spec:
#  project: default
#  sources:
#    - repoURL: https://prometheus-community.github.io/helm-charts
#      chart: kube-prometheus-stack
#      targetRevision: 79.4.0
#      helm:
#        valueFiles:
#          - $values/manifests/kube-prometheus-stack/eu-central-1-dev/values.yaml
#    - repoURL: file:///gitops
#      targetRevision: HEAD
#      ref: values
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: prometheus
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - ServerSideApply=true
#      - ApplyOutOfSyncOnly=true
