#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: prometheus-operator-crds
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    argocd.argoproj.io/sync-wave: "-2"
#spec:
#  project: default
#  source:
#    repoURL: https://prometheus-community.github.io/helm-charts
#    chart: prometheus-operator-crds
#    targetRevision: 25.0.0
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: monitoring
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - ServerSideApply=true
