apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kargo
  namespace: kargo
spec:
  parentRefs:
    - name: istio
      namespace: istio-system
      sectionName: https
  hostnames:
    - kargo.management.eu-central-1.localhost
  rules:
    - backendRefs:
        - name: kargo-api
          port: 80
