apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authorization-policy-allow-istio-gateway.yaml
  - cluster-role-kargo-controller-shard.yaml
  - cluster-role-binding-kargo-controller-shard.yaml
  - config-map-kargo-gitconfig.yaml
  - http-route-kargo.yaml
  - role-kargo-controller-secrets.yaml
  - role-binding-kargo-controller-secrets.yaml
  - secret-kargo-controller-shard-token.yaml
  - service-account-kargo-controller-shard.yaml
