apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-controller-secrets
  namespace: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-controller-secrets
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: kargo
