apiVersion: v1
kind: Secret
metadata:
  name: kargo-controller-shard-token
  namespace: kargo
  annotations:
    kubernetes.io/service-account.name: kargo-controller-shard
type: kubernetes.io/service-account-token
