apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-observability-backends
  namespace: minio
spec:
  rules:
    - from:
        - source:
            namespaces:
              - loki
              - mimir
              - tempo
