apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http-route-grafana.yaml
  - grafana-grafana.yaml
  - grafana-datasource-loki.yaml
  - grafana-datasource-mimir.yaml
  - grafana-datasource-tempo.yaml
