apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authz-allow-istio-gateway.yaml
  - authz-allow-within-namespace.yaml
  - httproute.yaml
  - grafana.yaml
  - datasource-loki.yaml
  - datasource-mimir.yaml
  - datasource-tempo.yaml
