apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authz-allow-alloy.yaml
  - authz-allow-istio-gateway.yaml
  - authz-allow-within-namespace.yaml
  - httproute.yaml
  - projects.yaml
