apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: management-wildcard
  namespace: istio-system
spec:
  secretName: management-wildcard-tls
  dnsNames:
    - "management.eu-central-1.localhost"
    - "*.management.eu-central-1.localhost"
  issuerRef:
    name: localhost-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
