apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-manager
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: istio-manager
    namespace: istio-system
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-manager-token
  namespace: istio-system
  annotations:
    kubernetes.io/service-account.name: istio-manager
type: kubernetes.io/service-account-token
