apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: tempo-otlp
  namespace: tempo
spec:
  parentRefs:
    - name: istio
      namespace: istio-system
      sectionName: observability
  rules:
    - backendRefs:
        - name: tempo
          port: 4317
