apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tempo-otlp-http
  namespace: tempo
spec:
  parentRefs:
    - name: istio
      namespace: istio-system
      sectionName: https
  hostnames:
    - tempo.management.eu-central-1.localhost
  rules:
    - backendRefs:
        - name: tempo
          port: 4318
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tempo-otlp-internal
  namespace: tempo
spec:
  parentRefs:
    - name: istio
      namespace: istio-system
      sectionName: observability
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /tempo
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: tempo
          port: 4318
