apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-eu-central-1
  namespace: phasor
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: phasor
      sources:
        stages:
          - int-eu-central-1
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-phasor
  verification: {}
