apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-within-namespace
  namespace: mimir
spec:
  rules:
    - from:
        - source:
            namespaces:
              - mimir
