apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - validating-admission-policy-require-resource-constraints.yaml
  - validating-admission-policy-binding-require-resource-constraints.yaml
