profile: ambient

global:
  meshID: management-eu-central-1
  multiCluster:
    clusterName: management-eu-central-1

pilot:
  autoscaleEnabled: false
  replicaCount: 1
  env:
    PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
  resources:
    requests:
      cpu: 40m
      memory: 128Mi
    limits:
      memory: 128Mi

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultProviders:
    tracing:
      - otel-tracing
  extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: alloy.alloy.svc.cluster.local
