cluster:
  name: monke-eu-central-1-dev

destinations:
#  - name: mimir
#    type: prometheus
#    url: http://mimir-gateway.mimir.svc.cluster.local:80/api/v1/push

  - name: loki
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push

clusterMetrics:
  enabled: false

clusterEvents:
  enabled: true

podLogs:
  enabled: true

nodeLogs:
  enabled: true

annotationAutodiscovery:
  enabled: false

prometheusOperatorObjects:
  enabled: false

alloy-metrics:
  enabled: false
  alloy:
    mounts:
      varlog: true
    clustering:
      enabled: true

alloy-logs:
  enabled: true

alloy-receiver:
  enabled: true

alloy-singleton:
  enabled: true
#  extraConfig: |-
#    mimir.rules.kubernetes "default" {
#      address = "http://mimir-ruler.mimir.svc.cluster.local:8080"
#    }
