apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eu-central-1-management
  namespace: argocd
spec:
  description: Platform components for the management cluster
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eu-central-1-dev
  namespace: argocd
spec:
  description: Applications for the dev cluster
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      name: eu-central-1-dev
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eu-central-1-prod
  namespace: argocd
spec:
  description: Applications for the prod cluster
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      name: eu-central-1-prod
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
