apiVersion: v1
kind: Secret
metadata:
  name: phasor-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: 'phasor'
  url: 'https://github.com/monkescience/phasor'
  type: 'git'
