apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - project-config.yaml
  - promotion-task.yaml
  - warehouse.yaml
  - stage-eu-central-1-dev.yaml
  - stage-eu-central-1-int.yaml
  - stage-eu-central-1-prod.yaml
  - stage-us-east-1-int.yaml
  - stage-us-east-1-prod.yaml
