apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: phasor
  namespace: phasor
spec:
  promotionPolicies:
    - stageSelector:
        name: eu-central-1-dev
      autoPromotionEnabled: true
