apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: us-east-1-prod
  namespace: phasor
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: phasor
      sources:
        stages:
          - us-east-1-int
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-phasor
  verification: {}
