apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: eu-central-1-int
  namespace: phasor
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: phasor
      sources:
        stages:
          - eu-central-1-dev
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-phasor
  verification: {}
