apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authorization-policy-allow-istio-gateway.yaml
  - http-route-argocd.yaml
  - app-project-platform.yaml
  - app-project-services.yaml
  - secret-phasor-repository.yaml
