auth:
  strategy: anonymous

deployment:
  replicas: 1
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

server:
  web_fqdn: kiali.management.eu-central-1.localhost

external_services:
  prometheus:
    url: http://mimir-gateway.mimir.svc.cluster.local:80/prometheus
  grafana:
    enabled: true
    internal_url: http://grafana-service.grafana.svc.cluster.local:3000
    external_url: https://grafana.management.eu-central-1.localhost:8443
  tracing:
    enabled: true
    provider: tempo
    internal_url: http://tempo.tempo.svc.cluster.local:3200
    external_url: https://grafana.management.eu-central-1.localhost:8443
    use_grpc: false
  istio:
    root_namespace: istio-system
