apiVersion: v1
kind: Namespace
metadata:
  name: kargo
  annotations:
    pod-security.kubernetes.io/reason: "kargo controller requires hostPath volume for local gitops repository mount"
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
