backend:
  replicaCount: 3
  config:
    environment: "us-east-1-prod"
    log_config:
      level: "warn"
      format: "json"
      add_source: false

frontend:
  replicaCount: 2
  config:
    environment: "us-east-1-prod"
    backend_url: "http://phasor-backend:8080/instance/info"
    log_config:
      level: "warn"
      format: "json"
      add_source: false
    tile_colors:
      - "#667eea"
      - "#f093fb"
      - "#4facfe"
      - "#43e97b"

dapr:
  enabled: false
