backend:
  replicaCount: 3
  config:
    environment: "eu-central-1-prod"
    log_config:
      level: "warn"
      format: "json"
      add_source: false

frontend:
  replicaCount: 2
  config:
    environment: "eu-central-1-prod"
    backend_url: "http://phasor-prod-backend/instance/info"
    log_config:
      level: "warn"
      format: "json"
      add_source: false
    tile_colors:
      - "#667eea"
      - "#f093fb"
      - "#4facfe"
      - "#43e97b"

httpRoute:
  enabled: true
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - phasor.prod.localhost
