backend:
  replicaCount: 1
  config:
    environment: "dev-eu-central-1"
    log_config:
      level: "debug"
      format: "json"
      add_source: true
  rollout:
    httpRoute:
      enabled: true
      parentRefs:
        - name: istio
          namespace: istio-system
          sectionName: https
      hostnames:
        - phasor.dev.eu-central-1.localhost
      pathPrefix: /api

frontend:
  replicaCount: 1
  config:
    environment: "dev-eu-central-1"
    backend_url: "http://phasor-dev-backend/instance/info"
    log_config:
      level: "debug"
      format: "json"
      add_source: true
    tile_colors:
      - "#667eea"
      - "#f093fb"
      - "#4facfe"
      - "#43e97b"

httpRoute:
  enabled: true
  parentRefs:
    - name: istio
      namespace: istio-system
      sectionName: https
  hostnames:
    - phasor.dev.eu-central-1.localhost
