apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - authz-allow-gateway-ingress.yaml
  - authz-default-deny.yaml
  - gateway.yaml
  - gateway-config.yaml
  - httproute-redirect.yaml
