apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - http-route-alloy.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alloy-config
    files:
      - config.alloy
