apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-map-istio-gateway-config.yaml
  - gateway-istio.yaml
  - http-route-http-to-https-redirect.yaml
  - telemetry-mesh-default.yaml
