apiVersion: v1
kind: Secret
metadata:
  name: reference-service-go-repository
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: 'reference-service-go'
  url: 'https://github.com/monkescience/reference-service-go'
  type: 'git'
