apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
spec:
  gatewayClassName: traefik
  listeners:
    - name: http
      port: 9080
      protocol: HTTP
      hostname: "*.localhost"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 9443
      protocol: HTTPS
      hostname: "*.localhost"
      tls:
        mode: Terminate
        certificateRefs:
          - name: localhost-wildcard-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
