apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-wildcard
  namespace: istio-system
spec:
  secretName: prod-wildcard-tls
  dnsNames:
    - "prod.eu-central-1.localhost"
    - "*.prod.eu-central-1.localhost"
  issuerRef:
    name: localhost-ca
    kind: ClusterIssuer
    group: cert-manager.io
