apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate-localhost-ca.yaml
  - cluster-issuer-localhost-ca.yaml
  - cluster-issuer-selfsigned.yaml
  - certificate-prod-wildcard.yaml
