backend:
  replicaCount: 3
  config:
    environment: "prod-eu-central-1"
    log_config:
      level: "warn"
      format: "json"
      add_source: false
  rollout:
    httpRoute:
      enabled: true
      parentRefs:
        - name: istio-gateway
          namespace: istio-system
          sectionName: https
      hostnames:
        - phasor.prod.eu-central-1.localhost
      pathPrefix: /api

frontend:
  replicaCount: 2
  config:
    environment: "prod-eu-central-1"
    backend_url: "http://phasor-prod-backend/instance/info"
    log_config:
      level: "warn"
      format: "json"
      add_source: false
    tile_colors:
      - "#667eea"
      - "#f093fb"
      - "#4facfe"
      - "#43e97b"

httpRoute:
  enabled: true
  parentRefs:
    - name: istio-gateway
      namespace: istio-system
      sectionName: https
  hostnames:
    - phasor.prod.eu-central-1.localhost
