apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  - grafana.yaml
  - datasource-loki.yaml
  - datasource-mimir.yaml
  - custom-mixin
  - kubernetes-mixin
  - node-exporter-mixin
