profile: ambient

gateways:
  seccompProfile:
    type: RuntimeDefault

global:
  meshID: prod-eu-central-1
  multiCluster:
    clusterName: prod-eu-central-1

pilot:
  autoscaleEnabled: false
  replicaCount: 1
  env:
    PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      memory: 128Mi

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultProviders:
    tracing:
      - otel-tracing
  extensionProviders:
    - name: otel-tracing
      opentelemetry:
        port: 4318
        service: alloy.alloy.svc.cluster.local
        http:
          path: /v1/traces
          timeout: 5s
