apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprconfig
  namespace: dapr-system
spec:
  mtls:
    enabled: true
    workloadCertTTL: "24h"
    allowedClockSkew: "15m"
    controlPlaneTrustDomain: "cluster.local"
    sentryAddress: "dapr-sentry.dapr-system.svc.cluster.local:443"

  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc

  metrics:
    enabled: true

  accessControl:
    defaultAction: allow
    trustDomain: "cluster.local"

  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
