global:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault

controller:
  # Default controller handles unassigned resources and management-specific resources
  shardName: management-eu-central-1
  isDefault: true
  globalCredentials:
    namespaces:
      - kargo
  env:
    - name: GIT_CONFIG_COUNT
      value: "1"
    - name: GIT_CONFIG_KEY_0
      value: safe.directory
    - name: GIT_CONFIG_VALUE_0
      value: /gitops
  volumes:
    - name: gitops
      hostPath:
        path: /gitops
        type: Directory
  volumeMounts:
    - name: gitops
      mountPath: /gitops
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

api:
  tls:
    enabled: false
  adminAccount:
    passwordHash: $2a$12$J3u7V0B2zYhsDsaxtaBXEOChOEbMcTJwhljitJOsQ3JTwRaaH4r.u # admin
    tokenSigningKey: 98daba3e93922ec98232bbdd1836e3d51f994b62ba4e485a7c70b81094263cc1
    tokenTTL: 24h
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

garbageCollector:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

externalWebhooksServer:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

managementController:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi

webhooksServer:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 64Mi
