apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project-phasor.yaml
  - warehouse-phasor.yaml
  - project-config-phasor.yaml
  - promotion-task-promote-phasor.yaml
  - stage-dev-eu-central-1.yaml
  - stage-prod-eu-central-1.yaml
