apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alloy.yaml
  - argo-rollouts.yaml
  - argocd.yaml
  - cert-manager.yaml
  - default.yaml
  - istio-system.yaml
  - kargo.yaml
  - kiali.yaml
  - kube-public.yaml
  - kube-state-metrics.yaml
  - kube-system.yaml
  - phasor.yaml
