# NOTE: After changing this ConfigMap, manually restart the Kargo controller:
#   kubectl rollout restart deploy/kargo-controller -n kargo --context kind-dev-eu-central-1
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-gitconfig
  namespace: kargo
data:
  gitconfig: |
    [safe]
      directory = *
    [receive]
      denyCurrentBranch = updateInstead
