apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: alloy-config
    files:
      - 00-common.alloy
      - 10-metrics.alloy
      - 20-logs.alloy
      - 30-traces.alloy
